### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [julianenochs/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [ ] The three attributes I chose for **Class #1** represent properties or characteristics.
> It seems like attributes and methods are more suited for an `Employee` class instead of a `Work schedule` class. 
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The three methods I chose for **Class #1** represent behaviors or actions.
> Try to name your methods as verbs/actions. Good examples here would be `calculate_pay`, `generate_timesheet`, and `check_full_time_status`
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class. 
> Same comment as above. The attributes and methods seem more like they belong to a specific employee than the entire month of March. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 
> Make sure that your commit messages are specific. When you're looking at all of your commits in the future, `Add values` will make it difficult to remember what that commit was all about. Try something like `Add example object #1` (or something like that). 

Class #2 Checklist
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The three methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
> Be specific with your commits. Maybe something like `Add reservation class with attributes and methods`? 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
> Same comment for this commit message as above 😄 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> You're super close! Overall, good. We want to see one more example a class so that we can update your score. 
> Next steps: Create one more file called class_3.txt and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called class_3_example_object.txt and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready
